[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
warp = "0.3"
dex-protocol-core = { path = "../core" }
dex-protocol-contracts = { path = "../contracts" }

[dependencies.reqwest]
version = "0.11"
features = ["json"]